---
- name: ssh key generate
  hosts: localhost
  tasks:
    - name: generate ssh key pairs
      user:
        name: guru
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/guru/.ssh/id_rsa

- name: copy public key
  hosts: all
  tasks:
    - name: using authorized module
      ansible.posix.authorized_key:
        user: guru
        state: present
        key: "{{ lookup('file', '/home/guru/.ssh/id_rsa.pub') }}"