---
- name: using file module
  hosts: servera.test.com
  gather_facts: false
  tasks:
    - name: make Dir
      file:
        path: /sunday
        state: directory
        mode: '0750'

    - name: create empty file 
      file: 
        path: /sunday/a.txt 
        owner: root
        group: wheel 
        mode: 0600
        state: touch   