---
- name: install web svr
  hosts: all
  serial: 3
  tasks:
    - name: using dnf
      dnf:
        name: httpd
        state: latest
      notify:
        - start_web


  handlers:
    - name: start_web
      service:
        name: httpd
        state: started
        enabled: true