---
- name: install web svr
  hosts: all
  tasks:
    - name: using dnf
      dnf: 
        name: httpd
        state: latest
      notify:
        - start_web  

  handlers:  
    - name: start_web 
      service:
        name: httpd
        state: start
        enabled: true    
